language: node_js
node_js:
  - "14"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - echo "markk.co" > build/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: build
keep-history: true