language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - echo "markk.co" > .vuepress/dist/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: .vuepress/dist
keep-history: true